name: "Repository Roster"

on: 
  watch:
    types:
      - started
  fork:
  
jobs:
  fetch_latest_info:
    name: "ğŸ”  Repository Roster"
    runs-on: ubuntu-latest
    steps:
      - name: "ğŸ“¥  Fetching Repository Contents"
        uses: actions/checkout@main
          
      - name: "ğŸ”  Markdown - Repository Roster"
        uses: varunsridharan/action-repository-roster@main
        with:
          STARS_OUTPUT_TYPE: 'markdown'
          FORK_OUTPUT_TYPE: 'markdown'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: "ğŸ”  Image - Repository Roster"
        uses: varunsridharan/action-repository-roster@main
        with:
          STARS: 'image.md'
          FORK: 'image.md'
          STARS_OUTPUT_TYPE: 'image'
          FORK_OUTPUT_TYPE: 'image'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
