name: "Repository Roster"

on: 
  watch:
    types:
      - started
  fork:
  
jobs:
  fetch_latest_info:
    name: "ğŸ”  Repository Roster"
    runs-on: ubuntu-latest
    steps:
      - name: "ğŸ“¥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "ğŸ”  Repository Roster"
        uses: varunsridharan/action-repository-roster@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
